### ISSUE TITLE
关于自定义模板的文件位置

### ISSUE THREAD

**Issue by WYLK0912** [mobyw/nonebot-plugin-txt2img#3]
我需要应用的插件位于xx/src/plugin/xxx目录，但是字体和图片文件位于xx/tem/img/11.png，这种时候，我该如何填写路径，是直接填写tem/img/11.png吗

**Comment by mobyw** [comment]
使用绝对路径和相对路径都可以，如果使用相对路径就是相对运行目录的路径，可以使用 `tem/img/11.png` 或者 `./tem/img/11.png`

**Comment by WYLK0912** [comment]
> 

谢谢
