### ISSUE TITLE
关于nonebot-plugin-saa

### ISSUE THREAD

**Issue by KolinLoa** [mobyw/nonebot-plugin-txt2img#4]
使用时会提示没有saa，仔细检查代码后才发现有saa这个插件，希望作者在readme可以标注一下

**Comment by mobyw** [comment]
python 包中已有明确的依赖关系，请使用包管理器进行 python 包的安装。

## 使用 `pip`

`pip install nonebot-plugin-txt2img`

`pip install git+https://github.com/mobyw/nonebot-plugin-txt2img`

## 使用 `poetry`

`poetry add nonebot-plugin-txt2img`

`poetry add git+https://github.com/mobyw/nonebot-plugin-txt2img`
