### ISSUE TITLE
字体较小时最后一行会缺一点

### ISSUE THREAD

**Issue by SonodaHanami** [mobyw/nonebot-plugin-txt2img#9]
`font_size` 为 `20` 时
![4D%NW5$IZS 4T6WQZ{F 8U4_tmb](https://github.com/mobyw/nonebot-plugin-txt2img/assets/31097812/7eae3302-6f79-4ccf-a95a-f5810759fdda)

如果为 `text_total_height` 加上 `content_font.size // 2` 
（相当于将 `(content_row_number - 1) * (content_font.size // 2)` 改为 `content_row_number * (content_font.size // 2)` ）
![$)ZHIXXL%~W8@D GHN~Z(07](https://github.com/mobyw/nonebot-plugin-txt2img/assets/31097812/4b74c8ac-b70a-4fe5-88aa-d1308a5cbfb6)
但是在字体较大时本来就没有缺失的问题，加上的半行空白会在行数较少时更明显
可能在paste的时候连同margin一起调整更好？

**Comment by SonodaHanami** [comment]
将文本图片粘贴到背景时纵坐标偏移加上 `font_size // 4` 🤔
![WVOX858KO` ~I} V}FX~BAE](https://github.com/mobyw/nonebot-plugin-txt2img/assets/31097812/b12b4b9d-e6ef-4772-97d1-652733196ff8)

**Comment by mobyw** [comment]
当前最后一行会在基线处截断

> 但是在字体较大时本来就没有缺失的问题，加上的半行空白会在行数较少时更明显

可以先在最后一行也添加一下行距解决文字基线以下部分的显示问题，后续根据textbox来进行细化调整

**Comment by mobyw** [comment]
已在版本 v0.4.1 中修复
